/**
 * IGDB's platforms, by id, onto the machines PlayRates already has (see
 * platform_systems). Keeping our own slugs means the platform marks, the
 * library filters and every log's chosen system stay as they were.
 *
 * PC is not here: which storefront it counts as depends on the game (see
 * pcSystem in the mapper).
 */
export const IGDB_PC = 6;

export const IGDB_SYSTEMS: Record<number, string> = {
  // PlayStation
  167: "playstation5",
  48: "playstation4",
  9: "playstation3",
  8: "playstation2",
  7: "playstation1",
  46: "ps-vita",
  38: "psp",
  // Xbox
  169: "xbox-series-x",
  49: "xbox-one",
  12: "xbox360",
  11: "xbox-old",
  // Nintendo
  130: "nintendo-switch",
  508: "nintendo-switch-2",
  41: "wii-u",
  5: "wii",
  21: "gamecube",
  4: "nintendo-64",
  19: "snes",
  58: "snes",
  18: "nes",
  99: "nes",
  37: "nintendo-3ds",
  137: "nintendo-3ds",
  20: "nintendo-ds",
  159: "nintendo-dsi",
  24: "game-boy-advance",
  22: "game-boy-color",
  33: "game-boy",
  // Mobile, Apple, Linux, web
  39: "ios",
  34: "android",
  14: "macos",
  75: "apple-ii",
  3: "linux",
  82: "web",
  // SEGA
  23: "dreamcast",
  32: "sega-saturn",
  29: "genesis",
  78: "sega-cd",
  30: "sega-32x",
  64: "sega-master-system",
  35: "game-gear",
  // Atari
  62: "jaguar",
  61: "atari-lynx",
  60: "atari-7800",
  66: "atari-5200",
  59: "atari-2600",
  65: "atari-8-bit",
  63: "atari-st",
  // Others with a family of their own
  16: "commodore-amiga",
  15: "commodore-amiga",
  80: "neogeo",
  79: "neogeo",
  50: "3do",
};

/** Which family each machine belongs to, as platform_systems has it. */
export const SYSTEM_FAMILY: Record<string, string> = {
  steam: "steam",
  "other-pc": "other-pc",
  playstation5: "playstation",
  playstation4: "playstation",
  playstation3: "playstation",
  playstation2: "playstation",
  playstation1: "playstation",
  "ps-vita": "playstation",
  psp: "playstation",
  "xbox-series-x": "xbox",
  "xbox-one": "xbox",
  xbox360: "xbox",
  "xbox-old": "xbox",
  "nintendo-switch": "nintendo-switch",
  "nintendo-switch-2": "nintendo-switch",
  "wii-u": "nintendo",
  wii: "nintendo",
  gamecube: "nintendo",
  "nintendo-64": "nintendo",
  snes: "nintendo",
  nes: "nintendo",
  "nintendo-3ds": "nintendo",
  "nintendo-ds": "nintendo",
  "nintendo-dsi": "nintendo",
  "game-boy-advance": "nintendo",
  "game-boy-color": "nintendo",
  "game-boy": "nintendo",
  ios: "mobile",
  android: "mobile",
  macos: "mac",
  "apple-ii": "mac",
  linux: "linux",
  web: "web",
  dreamcast: "sega",
  "sega-saturn": "sega",
  genesis: "sega",
  "sega-cd": "sega",
  "sega-32x": "sega",
  "sega-master-system": "sega",
  "game-gear": "sega",
  jaguar: "atari",
  "atari-lynx": "atari",
  "atari-7800": "atari",
  "atari-5200": "atari",
  "atari-2600": "atari",
  "atari-8-bit": "atari",
  "atari-st": "atari",
  "commodore-amiga": "commodore-amiga",
  neogeo: "neo-geo",
  "3do": "3do",
};
