import {
    BookOpen,
    Car,
    Castle,
    CircleDot,
    CircleHelp,
    Crosshair,
    Dices,
    Flag,
    Gamepad2,
    Hourglass,
    Joystick,
    Map,
    MousePointerClick,
    Music,
    Puzzle,
    Shapes,
    Swords,
    Target,
    Trophy,
    Users,
    Wrench,
    Zap,
    type LucideIcon,
} from "lucide-react";

/** A mark per genre, keyed by IGDB's slugs. An unknown one falls back to a
 *  controller rather than leaving a hole in the grid. */
const GENRE_ICONS: Record<string, LucideIcon> = {
    adventure: Map,
    arcade: Joystick,
    "card-and-board-game": Dices,
    fighting: Crosshair,
    "hack-and-slash-beat-em-up": Swords,
    indie: Shapes,
    moba: Users,
    music: Music,
    pinball: CircleDot,
    platform: Flag,
    "point-and-click": MousePointerClick,
    puzzle: Puzzle,
    "quiz-trivia": CircleHelp,
    racing: Car,
    "real-time-strategy-rts": Zap,
    "role-playing-rpg": Castle,
    shooter: Crosshair,
    simulator: Wrench,
    sport: Trophy,
    strategy: Castle,
    tactical: Target,
    "turn-based-strategy-tbs": Hourglass,
    "visual-novel": BookOpen,
};

export const genreIcon = (slug: string): LucideIcon =>
    GENRE_ICONS[slug] ?? Gamepad2;
